name: good_framework
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  window_manager: ^0.2.5
  provider: ^6.0.3
  google_fonts: ^3.0.1
  fluttertoast: ^8.0.9
  percent_indicator: ^4.2.2
  pull_to_refresh: ^2.0.0
  flutter_easyrefresh: ^2.2.2
  url_launcher: ^6.1.5
  get: ^4.6.5
  simple_animations: ^4.2.0
  flutter_slidable: ^2.0.0
  auto_animated: ^3.0.1
  animations: ^2.0.3
  animate_do: ^2.1.0
  carousel_slider: ^4.1.1

  like_button: ^2.0.4
  sign_button: ^2.0.2
  group_button: ^5.2.0
  dropdown_button2: ^1.6.3
  slider_button: ^2.0.0
  rounded_loading_button: ^2.1.0
  flutter_reaction_button: ^2.0.1+2
  animated_button: ^0.2.0
  slidable_button: ^2.0.0+1

  table_calendar: ^3.0.6
  syncfusion_flutter_calendar: ^20.2.40
  calendar_view: ^0.0.5
  date_picker_timeline: ^1.2.3
  flutter_calendar_carousel: ^2.4.0
  calendar_timeline: ^1.0.5
  flutter_neat_and_clean_calendar: ^0.3.7+21

  dotted_line: ^3.1.0
  patterns_canvas: ^0.4.0
  hand_signature: ^2.3.0+1
  touchable: ^1.0.2
  flutter_painter: ^1.0.1
  arrow_path: ^3.0.0

  # flutter_colorpicker: ^1.0.3
  emoji_picker_flutter: ^1.3.0
  day_night_time_picker: ^1.1.2
  flex_color_picker: ^2.5.0
  flutter_material_pickers: ^3.1.4+1
  smart_select: ^4.3.2
  adaptive_theme: ^2.3.1
  intl: ^0.17.0
  filesystem_picker: ^3.0.0
  permission_handler: ^8.0.3
  wechat_assets_picker: ^7.3.2
  bottom_picker: ^1.9.1
  flutter_picker: ^2.0.5
  progressive_time_picker: ^0.0.4
  flutter_datetime_picker: ^1.5.1

  ndialog: ^4.1.1+1
  rflutter_alert: ^2.0.4
  custom_pop_up_menu: ^1.2.4
  show_more_text_popup: ^0.3.0
  adaptive_dialog: ^1.7.0
  flutter_speed_dial: ^6.0.0
  simple_fontellico_progress_dialog: ^0.2.1
  flutter_smart_dialog: ^4.5.3+7
  flutter_animated_dialog: ^2.0.1
  modal_bottom_sheet: ^2.1.0

  sn_progress_dialog: ^1.0.8
  cupertino_stepper: ^0.2.1
  liquid_progress_indicator: ^0.4.0
  modal_progress_hud_nsn: ^0.2.1
  flutter_svprogresshud: ^1.0.0
  sleek_circular_slider: ^2.0.1
  flutter_animation_progress_bar: ^2.2.1
  photo_manager: ^2.1.4


  intro_slider: ^3.0.9
  lazy_load_scrollview: ^1.3.0
  fading_edge_scrollview: ^3.0.0
  flutter_scroll_to_top: ^2.2.4
  extended_nested_scroll_view: ^5.1.1
  extended_image: any
  ff_annotation_route_library: ^3.0.0
  loading_more_list: any
  pull_to_refresh_notification: any


  flutter_advanced_segment: ^3.0.1
  flutter_segment: ^3.9.0
  animated_segment: ^0.0.4
  animated_segmented_tab_control: ^1.0.1

  # flutter_onboarding_slider: ^1.0.7
  # syncfusion_flutter_sliders: ^20.2.40
  # flutter_slider_drawer: ^2.1.1
  # introduction_slider: ^1.0.0
  # another_xlider: ^1.1.2
  # vertical_weight_slider: ^2.4.0
  # slide_to_confirm: ^1.1.0

  # flutter_switch: ^0.3.2
  # toggle_switch: ^2.0.1
  # flutter_advanced_switch: ^3.0.1
  # list_tile_switch: ^1.0.0
  # animated_theme_switcher: ^2.0.6
  # font_awesome_flutter: ^10.1.0
  # animated_toggle_switch: ^0.5.2

  # grouped_list: ^5.1.2
  # inview_notifier_list: ^3.0.0
  # group_list_view: ^1.1.1
  # searchable_listview: ^2.0.0
  # indexed_list_view: ^2.0.2
  # flutter_staggered_animations: ^1.0.0
  # # azlistview: ^2.0.0
  # data_tables: ^1.4.0
  # data_table_2: ^2.3.5
  # infinite_scroll_pagination: ^3.2.0
  # custom_refresh_indicator: ^1.2.1
  # filter_list: ^1.0.2
  # sticky_grouped_list: ^3.1.0
  # accordion: ^2.5.1
  # scrollable_positioned_list: ^0.3.2
  # draggable_scrollbar: ^0.1.0
  # flutter_wall_layout: ^2.1.1
  # flutter_layout_grid: ^2.0.1
  # responsive_table: ^0.2.0+2
  # scroll_to_index: ^3.0.1

  
  cached_network_image: ^3.2.1
  lottie: ^1.4.1
  logging: ^1.0.2


  vertical_scrollable_tabview:
    path: ../lr_plugins/vertical_scrollable_tabview
  flutter_colorpicker: ^1.0.3
  phosphor_flutter: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  assets:
    - assets/images/
    - assets/lottie/

  fonts:
    - family: JinNianYeYaoJiaYouYa
      fonts:
        - asset: assets/fonts/JinNianYeYaoJiaYouYa.ttf

    - family: AaLieHuoXingKai
      fonts:
        - asset: assets/fonts/AaLieHuoXingKai.ttf

    - family: QingNiaoHuaGuangXingKai
      fonts:
        - asset: assets/fonts/QingNiaoHuaGuangXingKai.ttf

    - family: AaKaiSong
      fonts:
        - asset: assets/fonts/AaKaiSong.ttf

    - family: Ngaan
      fonts:
        - asset: assets/fonts/Ngaan.ttf

    - family: Comic Neue
      fonts:
        - asset: assets/fonts/Comic-Neue.ttf
    - family: Helvetica
      fonts:
        - asset: assets/fonts/Helvetica.ttf
    - family: Helvetica Neue
      fonts:
        - asset: assets/fonts/Helvetica-Neue.ttf
    - family: Open Sans
      fonts:
        - asset: assets/fonts/Open-Sans.ttf
    - family: PT Serif
      fonts:
        - asset: assets/fonts/PT-Serif.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto.ttf
    - family: Noto Emoji
      fonts:
        - asset: assets/fonts/Noto-Emoji.ttf
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
